spring:
  application:
    name: msdemo-config-center
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888
  #port: 8889
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      #defaultZone: http://dhcc:dhcc123@localhost:8761/eureka/,http://dhcc:dhcc123@localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/

#监控相关配置  
management:
  security:
    enabled: false      
info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"