logging:
  level:
    root: INFO
    #org.springframework.security: INFO
    org.springframework.cloud:  DEBUG
    org.springframework.boot: DEBUG

#监控相关配置  
management:
  security:
    enabled: false
    
#Feign hystix
feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000