server:
  context-path: /
  port: 9091

debug: false


#数据库版本管理
flyway:
  enabled: true
  table: DEMO_SCHEMA_VERSION

#JDBC-MySQL
spring:
  datasource:
#    url: jdbc:mysql://39.106.61.229:3306/springclouddb?characterEncoding=utf8
#    username: springclouddb
#    password: springclouddb
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:32768/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false

    username: root
    password: ryouka123456
    driver-class-name: com.mysql.jdbc.Driver
    #schema: classpath:/mysql.sql # zipkin schema 移除,放置在V1_DDL_init_schema.sql
    initialize: true
    continueOnError: true
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:h2:file:~/.h2/testdb
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
    # 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      min-evictable-idle-time-millis: 100000
      validation-query: select 1
      ######Druid监控配置######
      #下面配置说明请参考Druid Github Wiki，配置_配置WebStatFilter
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #下面配置说明请参考Druid Github Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid
  sleuth:
    enabled: false
        
turbine:
  #instanceInsertPort:
  #  default: false
  combineHostPort: true
  aggregator:
    clusterConfig: PRDT-CONSUMER, PRDT-PROVIDER  #default # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: prdt-consumer,prdt-provider,msdemo-msims-admin   # 配置Eureka中的serviceId列表，表明监控哪些服务,对应的是“熔断器状态”
  clusterNameExpression: metadata['cluster'] #new String("default") #metadata['cluster'] #"'default'"
#  instanceUrlSuffix:
#    PRDT-CONSUMER: /prdt-consumer/hystrix.stream
#    PRDT-PROVIDER: /prdt-provider/hystrix.stream

# 上述示例监控路径为:http://localhost:9091/turbine.stream?cluster=PRDT-CONSUMER , 实际路径为clusterConfig下配置的名称

#mybatis相关配置
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml

zipkin:
  storage:
    type: mysql
    StorageComponent: mysql

