server:
  context-path: /msdemo-msims-admin
  port: 9092

#数据库版本管理
flyway:
  enabled: true
  table: DEMO_SCHEMA_VERSION

#JDBC-MySQL
spring:
  datasource:
#    url: jdbc:mysql://39.106.61.229:3306/springclouddb?characterEncoding=utf8
#    username: springclouddb
#    password: springclouddb
#    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 10
      min-evictable-idle-time-millis: 100000
      validation-query: select 1
      ######Druid监控配置######
      #下面配置说明请参考Druid Github Wiki，配置_配置WebStatFilter
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #下面配置说明请参考Druid Github Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid
#JDBC-H2

#mybatis相关配置
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
